package view;

import dao.absensiDAO;
import java.awt.Cursor;
import javax.swing.table.DefaultTableModel;
import java.util.List;
public class MenuMahasiswa extends javax.swing.JFrame {
    String nimSession;
    public MenuMahasiswa(String nim) {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        initbutton();
        this.nimSession=nim;     
        getDataMhs();
        getStatistik();
        tampilRiwayatAbsen();
    }
    private void initbutton(){
    btnrekap.setContentAreaFilled(false);
    btnrekap.setFocusPainted(false);
    btnrekap.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
    }
    public void getDataMhs(){
        dao.mahasiswaDAO dao = new dao.mahasiswaDAO();
        model.mahasiswa data = dao.getProfil(nimSession);
        if (data != null) {
            lNama.setText("Selamat Datang, "+data.getNama());
            lNim.setText("Nim : "+data.getNim());
        } else{
            lNama.setText("tidak ada mahasiswa dengan nim tersebut");
        }
        
    }
    public void getStatistik(){
        dao.absensiDAO dao = new dao.absensiDAO();
        model.rekapAbsensi data = dao.getRekapAbsensi(nimSession);
        TFhadir.setText("Hadir : "+data.getTotalHadir());
        TFsakit.setText("Sakit : "+data.getTotalSakit());
        TFalpa.setText("Alpa : "+data.getTotalAlpa());
        TFizin.setText("Izin : "+data.getTotalIzin());
    }
    
    public void tampilRiwayatAbsen(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        absensiDAO dao = new absensiDAO();
        List<String[]> dataRiwayat = dao.getRiwayatAbsensi(nimSession);
        
        for (String[] row : dataRiwayat) {
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnrekap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lNim = new javax.swing.JLabel();
        TFsakit = new javax.swing.JTextField();
        TFhadir = new javax.swing.JTextField();
        TFalpa = new javax.swing.JTextField();
        TFizin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-close-32.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(830, 10, 32, 29);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnrekap.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnrekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-notebook-50.png"))); // NOI18N
        btnrekap.setText("Rekap Absen");
        btnrekap.setToolTipText("");
        btnrekap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnrekap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnrekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrekapActionPerformed(evt);
            }
        });
        jPanel1.add(btnrekap);
        btnrekap.setBounds(20, 230, 180, 60);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("E - ABSEN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(238, 67, 94, 24);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("E - ABSEN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 60, 90, 24);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logopolnep.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 100, 100, 100);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 210, 470);

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Mata Kuliah", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(250, 220, 590, 230);

        lNim.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lNim.setForeground(new java.awt.Color(255, 255, 255));
        lNim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lNim.setText("nim");
        lNim.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lNim);
        lNim.setBounds(250, 80, 560, 30);

        TFsakit.setEditable(false);
        TFsakit.setBackground(new java.awt.Color(51, 153, 255));
        TFsakit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TFsakit.setText("Sakit :");
        jPanel2.add(TFsakit);
        TFsakit.setBounds(660, 140, 100, 40);

        TFhadir.setEditable(false);
        TFhadir.setBackground(new java.awt.Color(51, 204, 0));
        TFhadir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TFhadir.setText("Hadir :");
        TFhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhadirActionPerformed(evt);
            }
        });
        jPanel2.add(TFhadir);
        TFhadir.setBounds(330, 140, 100, 40);

        TFalpa.setEditable(false);
        TFalpa.setBackground(new java.awt.Color(204, 51, 0));
        TFalpa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TFalpa.setText("Alpa :");
        TFalpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFalpaActionPerformed(evt);
            }
        });
        jPanel2.add(TFalpa);
        TFalpa.setBounds(550, 140, 100, 40);

        TFizin.setEditable(false);
        TFizin.setBackground(new java.awt.Color(255, 204, 0));
        TFizin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TFizin.setText("Izin :");
        TFizin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFizinActionPerformed(evt);
            }
        });
        jPanel2.add(TFizin);
        TFizin.setBounds(440, 140, 100, 40);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Riwayat Absensi Terakhir");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(250, 190, 240, 24);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Statistik Kehadiran");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(290, 110, 180, 24);

        lNama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lNama.setText("nama");
        lNama.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lNama);
        lNama.setBounds(250, 50, 560, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnrekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrekapActionPerformed
//        new MenuMahasiswa().setVisible(true);
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_btnrekapActionPerformed

    private void TFhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhadirActionPerformed

    private void TFizinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFizinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFizinActionPerformed

    private void TFalpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFalpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFalpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuMahasiswa().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFalpa;
    private javax.swing.JTextField TFhadir;
    private javax.swing.JTextField TFizin;
    private javax.swing.JTextField TFsakit;
    private javax.swing.JButton btnrekap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lNim;
    // End of variables declaration//GEN-END:variables
}
